### ISSUE TITLE
Should setting npm as the package manager still display Commands ("yarn run COMMAND"):

### ISSUE THREAD

**Issue by abelmokadem** [eladb/projen#217]
Currently the terminal after running projen with `packageManager: NodePackageManager.NPM` is still showing:

`Commands ("yarn run COMMAND"):`

instead of

`Commands ("npm run COMMAND"):`

**Comment by Chriscbr** [comment]
Right now the string is just hardcoded in: 
https://github.com/eladb/projen/blob/6847053eddbb5ab8847c89e3f11d16f3023d0af1/src/cli/cmds/start-app.ts#L31

I'm not sure offhand how to go about implementing the bug fix, since it seems like the CLI tool generally doesn't have access to the entire set of projenrc.js options at runtime. One way I could see this being worked around is by adding some kind of extra metadata field in one of the generated config files (maybe `package.json`) which specifies the package manager choice, and then reading from that during the CLI tool's execution -- but maybe there's a simpler solution I haven't considered.

In principle you might be able to tell which package manager is set based on the presence of `package-lock.json` or `yarn.lock` files, but I don't think that would be reliable either.
